# Estadistica Aplicada
## 2da Sion
**26 deEnero**

In [1]:
pip install yfinance

Note: you may need to restart the kernel to use updated packages.


In [2]:
import yfinance as yf

In [4]:
import numpy as np

In [51]:
edades = [12, 18, 25, 32, 40]

In [52]:
type(edades)

TypeError: 'list' object is not callable

In [53]:
edades=np.array(edades)

In [66]:
type(edades)

TypeError: 'list' object is not callable

In [55]:
np.mean(edades)

25.4

In [56]:
np.var(edades)

98.24000000000001

In [57]:
np.var(edades,ddof=1)

122.80000000000001

In [58]:
np.std(edades)

9.911609354691095

In [59]:
np.std(edades,ddof=1)

11.081516141756055

In [61]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [69]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
np.ones(3)

array([1., 1., 1.])

In [71]:
np.full(6,9)

array([9, 9, 9, 9, 9, 9])

In [95]:
np.random.seed(15)
np.random.randint(0,25,10)

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [97]:
np.random.seed(15)
aleatorios=np.random.randint(0,25,10)

In [98]:
aleatorios

array([ 8, 21, 12,  5, 23,  0,  7, 11, 21, 22])

In [100]:
aleatorios= np.sort(aleatorios)

In [102]:
aleatorios[3]

8

In [105]:
aleatorios[[3,5]]

array([ 8, 12])

In [106]:
aleatorios>5

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [107]:
aleatorios[aleatorios>5]

array([ 7,  8, 11, 12, 21, 21, 22, 23])

In [115]:
numeros = [1.23, 2.45578, 5.6888785]
numeros=np.array(numeros)

In [116]:
np.mean(numeros)

3.1248861666666667

In [117]:
numeros.mean()

3.1248861666666667

In [118]:
round(np.mean(np.array(numeros)),2)

3.12

In [121]:
np.array(numeros).mean().round(2)

3.12